name: safipay_app
description: "SafiPay Premium Digital Banking App"
# جلوگیری از انتشار تصادفی در pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # مدیریت دیتابیس و احراز هویت SafiPay
  supabase_flutter: ^2.12.4
  get: ^4.6.6
  google_fonts: ^8.0.2
  flutter_dotenv: ^6.0.1
  cupertino_icons: ^1.0.8
  animated_custom_dropdown: ^3.1.1
  url_launcher: ^6.3.2
  intl: ^0.20.2
  local_auth: ^3.0.1
  http: ^1.2.0 
  image_picker: ^1.2.1
  # لیست مکمل کشورها برای افتتاح حساب بین‌المللی
  country_picker: ^2.0.27

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # ابزار ساخت خودکار آیکون برای اندروید و iOS
  flutter_launcher_icons: ^0.13.1

# تنظیمات اختصاصی آیکون برند SafiPay
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#000000" # پس‌زمینه مشکی برندت
  adaptive_icon_foreground: "assets/images/logo.png"
flutter:
  uses-material-design: true
  
  # دارایی‌های برنامه شامل تنظیمات محیطی و لوگوی رسمی
  assets:
    - .env
    - assets/logo.png